# Generated by Django 3.1.5 on 2021-03-19 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorrorSubGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=255)),
                ('genredescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'horrorsubgenres',
                'db_table': 'horrorsubgenre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(max_length=255)),
                ('moviereleasedate', models.DateField()),
                ('moviedirector', models.CharField(max_length=255)),
                ('moviedescription', models.TextField(blank=True, null=True)),
                ('horrorsubgenre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='horror.horrorsubgenre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'movies',
                'db_table': 'movie',
            },
        ),
    ]
